services:

  pangolin:
    image: fosrl/pangolin:${PANGOLIN_VERSION:-postgresql-latest}
    depends_on: [database]
    env_file: environment.d/pangolin.env
    environment:
      SERVER_SECRET: ${SERVER_SECRET}
      POSTGRES_CONNECTION_STRING: postgresql://${DATABASE_USER:-pangolin}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME:-pangolin}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${PANGOLIN_CONFIG_PATH:-./volumes/config}:/app/config
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: curl -f http://localhost:3001/api/v1/
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  gerbil:
    image: fosrl/gerbil:${GERBIL_VERSION:-latest}
    depends_on:
      pangolin:
        condition: service_healthy
    cap_add: [NET_ADMIN, SYS_MODULE]
    env_file: environment.d/gerbil.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://${DATABASE_USER:-pangolin}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME:-pangolin}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - ${HTTP_PORT:-127.0.0.1:80}:80
      - ${SSL_PORT:-127.0.0.1:443}:443
      - ${SITE_TUNNEL_PORT:-51820}:51820/udp
      - ${CLIENT_TUNNEL_PORT:-21820}:21820/udp
    volumes:
      - ${PANGOLIN_CONFIG_PATH:-./volumes/config}:/var/config
      - /etc/localtime:/etc/localtime:ro
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    depends_on:
      pangolin:
        condition: service_healthy
    env_file: environment.d/traefik.env
    network_mode: service:gerbil
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${PANGOLIN_CONFIG_PATH:-./volumes/config}/traefik:/etc/traefik:ro
      - ${PANGOLIN_CONFIG_PATH:-./volumes/config}/letsencrypt:/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    command: [--configFile=/etc/traefik/traefik_config.yml]
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  database:
    image: postgres:${POSTGRES_VERSION:-17}
    env_file: environment.d/database.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-pangolin}
      POSTGRES_USER: ${DATABASE_USER:-pangolin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${DATABASE_DATA_PATH:-./volumes/database}:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: pg_isready -d ${DATABASE_NAME:-pangolin} -U ${DATABASE_USER:-pangolin}
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  database-backups:
    image: prodrigestivill/postgres-backup-local:${POSTGRES_BACKUP_VERSION:-latest}
    depends_on: [database]
    env_file: environment.d/database-backups.env
    environment:
      POSTGRES_HOST: ${DATABASE_HOST:-database}
      POSTGRES_DB: ${DATABASE_NAME:-pangolin}
      POSTGRES_USER: ${DATABASE_USER:-pangolin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /backups
    volumes:
      - ${DATABASE_BACKUPS_PATH:-./volumes/backups}:/backups
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
